### ISSUE TITLE
Home Button Detection Issue with Fire OS 5

### ISSUE THREAD

**Issue by SnappyFPV** [sphinx02/FireStarter#8] opened 2015-08-23 20:17 UTC
Shows repeating popup with issue ADB - Home Button Detection ...

**Comment by sphinx02** [comment] 2015-08-24 08:43
Hello,
here some results of my deeper analysis of the Fire OS 5 developer preview:
- After a reboot no (TCP based) ADB connections are possible at all, neither for FireStarter nor for any PC from outside. One have to move to the dev settings and disable + re-enable to connect via ADB.
- Only one (TCP based) ADB connection in parallel is possible. Every further connection shows only an "offline" device in ADB. That means if the background-observer of FireStarter is active (and connected), you can not connect from the PC and the way round (to be more correct, connection is possible but for the second connector, the device is shown offline).
- For the one that connects first, ADB seems to work completely as expected. Also FireStarter works completely as expected.

I hope and I am quite sure, that in the final Fire OS 5 version this buggy ADB behaviour will be fixed so I wont investigate further in this problematic. For everyone who is using the dev preview, I suggest to disable and reenable ADB after a reboot and further deactivate the background-observation in the FireStarter settings if you want to connect from your PC.

**Comment by Gertbucket** [comment] 2015-10-05 08:36
Multiple reports state the issue remains unresolved in the release shipped with Fire 2, and soon to be rolled out to older devices, probably this week. Here is one such review:

http://stadt-bremerhaven.de/amazon-fire-tv-2015-probleme-mit-mediencenter-kodi/

No pressure, but right now, it seems the entire AFTV community seems to have annointed you as the saviour capable of working a way around it.

Good luck!

**Comment by sphinx02** [comment] 2015-10-05 12:05
Ok, I have no own FireTV 2, but as soon as the official FireOS 5 is shipped out to the FireTV or FireTV Stick I will start to investigate in a solution. Perhaps you can keep me up to date when the FireOS 5 is shipped out to the older devices! Thank you :)

**Comment by Gertbucket** [comment] 2015-10-05 16:10
OS 5 preview received an update over the weekend. There remains some confusion as to whether this is the final but it seems logical that it would be given the timing. Those who've already received their FireTV 2 say the issue and workaround you identified continues.

I won't receive my new FireTV2 until later in the week, and I've rolled back the Dev OS so I can't comment first hand. I imagine you'll start seeing increased activity in your XDA thread shortly.

All the best, and, thank you for taking up the challenge!

**Comment by vip32** [comment] 2015-10-05 19:34
just received my aftv2 and can confirm that firestarter stopped working :( nooooo
this message appears every 10 seconds or so: something went wrong, restarting HomeButtonObserver now

Fire OS 5.0.2.1, adbFire works fine

**Comment by Gertbucket** [comment] 2015-10-05 19:44
Here's an email I received from Jeremy, the App shortcuts dev. 

He's also commented on Reddit here:

https://www.reddit.com/r/fireTV/comments/3nlran/broken_apps_in_new_fire_tv/

...........................................

Hello and thanks for signing up to receive updates. You'll receive these emails whenever there is an upcoming app update.

App Shortcuts and Fire OS 5

A few moments ago the new Fire TV arrived at my door and confirmed many of my suspicions about Fire OS 5. When the developer preview was released a few months ago, I noticed that the remote function stopped working. I figured it was just a bug in the preview.

Like with Android TV and many other Android devices, Fire OS 5 blocks the creation of local abd connections. The App Shortcuts server app uses this connection to control the screen with using the remote. So until I can find a work around, these features will not function properly.

It isn't all bad, I guess. The new Fire TV is pretty quick and so launching apps works really well. In the end, if no work around can be found App Shortcuts may return to just being a simple Fire TV launcher.

If you're able, please stay on your current version of Fire OS. Everything will continue to work as long as you don't update.

Thanks for your support. I'll keep you all posted.  --Jeremy 

Twitter: QuiverApps  Facebook: App Shortcuts

.........................................................

**Comment by jdrobert** [comment] 2015-10-06 13:43
Hey, this is Jeremy. @sphinx02 I'd be happy to help in anyway I can. It looks like the dev for "Remote Mouse for Fire TV" got his app to work. There must be a way.

**Comment by gbrooke** [comment] 2015-10-06 20:41
If u are the proud owner of the new Amazon firetv 4K box and you are having problems with firestarter after installing it ..
Reboot box - developers options - ADB debugging turn it off then back on then launch firestarter and it will work perfectly
Hope this helps

**Comment by Gertbucket** [comment] 2015-10-07 08:00
Who do you think came up with that advice?

**Comment by sphinx02** [comment] 2015-10-09 07:40
Disable & enable ADB after reboot is not anymore needed. Still no parallel ADB connections possible. Jumpback Watchdog problems are fixed, you can safely set it back to default of 5000ms.

see https://github.com/sphinx02/FireStarter/releases/tag/v3.0

**Comment by Gertbucket** [comment] 2015-10-09 08:11
Congratulations! This is excellent news.

**Comment by sphinx02** [comment] 2015-10-15 08:16
Problems with FireOS5 fixed in v3.0 and v3.1:
https://github.com/sphinx02/FireStarter/releases/tag/v3.0
https://github.com/sphinx02/FireStarter/releases/tag/v3.1

**Closed as completed by sphinx02** 2015-10-15 08:16 UTC
